### ISSUE TITLE
Allow access to nearby POI with lat long inputs

### ISSUE THREAD

**Issue by qtrandev** [CyberStrike/miami-transit-api#1]
http://www.miamidade.gov/transit/WebServices/Nearby/?Lat=&Long=
Ex: http://www.miamidade.gov/transit/WebServices/Nearby/?Lat=25.787057&Long=-80.189107

**Comment by qtrandev** [comment]
What is the current link to access this information? Use this?
https://sleepy-eyrie-8607.herokuapp.com/nearby.json?Lat=25.787057&Long=-80.189107

**Comment by CyberStrike** [comment]
I need to update and document the endpoint. :frowning: 

https://miami-transit-api.herokuapp.com/nearby.json?Lat=25.787057&Long=-80.189107
