### ISSUE TITLE
Can we have this app hosted on Heroku and always online?

### ISSUE THREAD

**Issue by qtrandev** [CyberStrike/miami-transit-api#4]
I need an always-on server before I switch the data source for LeafletTransit project.

**Comment by CyberStrike** [comment]
Uhm.. it's about $30 a month for always on. If you have a cheaper server we could move it there. I've always wanted to learn how deploy on something else.

**Comment by qtrandev** [comment]
I guess what I mean is I need the server to be online for me to test, so maybe less than 1000 requests a day. What options do we have?
-Does Heroku charge for something with this low usage?
-I use NameCheap for hosting, so does NameCheap or another low-cost host provide hosting for a Ruby on Rails app?

If it's more than $5 a month, I don't think I'm going to pay that. Eventually though, someone has to pay the cost for hosting this API server that grabs transit data from various places.

**Comment by qtrandev** [comment]
There is no issue here. Heroku just goes to sleep and takes about 15 seconds to come back online.
